# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Shield"
baseurl: /shield
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
repository: "RetailMeNot/shield"

# Build settings
markdown: kramdown

exclude: ['Gemfile', 'Gemfile.lock']

collections:
  releases:
    output: true

permalink: pretty

defaults:
  - scope:
      path: ""
      type: releases
    values:
      layout: release
